# Generated by Django 3.0.5 on 2020-05-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('image', models.ImageField(default='pics/user.png', upload_to='pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=6)),
                ('is_activated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CompQuestion',
            fields=[
                ('comp_id', models.CharField(auto_created=True, max_length=50, primary_key=True, serialize=False)),
                ('date_added', models.DateField()),
                ('question', models.TextField()),
                ('input_pattern', models.TextField()),
                ('output_pattern', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.CharField(auto_created=True, max_length=50, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('courseType', models.CharField(max_length=50)),
                ('courseCat', models.CharField(max_length=50)),
                ('courseDescription', models.TextField()),
                ('courseLink', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='coursePics/')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('test_comp', models.CharField(max_length=55)),
                ('study_materials', models.CharField(max_length=55)),
                ('compiler', models.CharField(max_length=55)),
                ('overall', models.CharField(max_length=55)),
                ('suggestion', models.TextField()),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JoinedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('is_joined', models.BooleanField()),
                ('joinedCourse', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('rpassword', models.CharField(max_length=15)),
                ('image', models.ImageField(default='pics/user.png', upload_to='pics/')),
            ],
        ),
        migrations.CreateModel(
            name='WeekTest',
            fields=[
                ('test_id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('test_category', models.CharField(max_length=55)),
                ('full_marks', models.PositiveIntegerField()),
                ('date_added', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='WeekTestResult',
            fields=[
                ('user', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('result', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.WeekTest')),
            ],
        ),
        migrations.CreateModel(
            name='WeekTestQuestion',
            fields=[
                ('question_id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(choices=[('A', 'option1'), ('B', 'option2'), ('C', 'option3'), ('D', 'option4')], max_length=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.WeekTest')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=50, primary_key=True, serialize=False)),
                ('topicLabel', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('headingId', models.CharField(auto_created=True, max_length=55, primary_key=True, serialize=False)),
                ('headingLabel', models.CharField(max_length=255)),
                ('headingText', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='CompResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=55)),
                ('result', models.PositiveIntegerField()),
                ('passed', models.PositiveIntegerField()),
                ('competitionQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.CompQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='CompQuesTestCase',
            fields=[
                ('id', models.PositiveIntegerField(auto_created=True)),
                ('testcase_id', models.CharField(auto_created=True, max_length=50, primary_key=True, serialize=False)),
                ('input', models.TextField(default='')),
                ('output', models.TextField()),
                ('competitionQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.CompQuestion')),
            ],
        ),
    ]
